import turtle
window=turtle.Screen()
window.bgcolor("#11ff00")
window.title("Farnam's Pen Code")
turtle_pen=turtle.Pen()
turtle_pen.pencolor("#1500ff")
turtle_pen.forward(25)
turtle_pen.left(90)
turtle_pen.forward(60)
turtle_pen.right(90)
turtle_pen.forward(40)
turtle_pen.left(90)
turtle_pen.forward(25)
turtle_pen.left(90)
turtle_pen.forward(40)
turtle_pen.right(90)
turtle_pen.forward(35)
turtle_pen.right(90)
turtle_pen.forward(55)
turtle_pen.left(90)
turtle_pen.forward(25)
turtle_pen.left(90)
turtle_pen.forward(80)
turtle_pen.left(90)
turtle_pen.forward(145)
turtle_pen.left(90)
turtle_pen.forward(26)
turtle_pen.pencolor("#11ff00")
turtle_pen.forward(120)
turtle_pen.pencolor("#1500ff")
turtle_pen.speed(0)
for counter in range(420):
    turtle_pen.forward(1.1)
    turtle_pen.left(.9)